### ISSUE TITLE
ディレクトリ構成について

### ISSUE THREAD

**Issue by igoigo15** [Trunkene/volumio_jpradio#1]
Install手順において順に進み、
(venv) volumio@volumio:~/bin$ git clone https://github.com/Trunkene/volumio_jpradio .
としたところ、
fatal: destination path '.' already exists and is not an empty directory.
とエラーとなったので、適当な場所にgit cloneし、
$ mv /volumio_jpradio/bin/* ~/bin
として~/bin配下を
dlradiko.sh  ffmpeg  pgupdate.sh  radiko
としました。
この状態で以下radikoを実行すると、

(venv) volumio@volumio:~/bin$ radiko
 * Serving Flask app 'run.py' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Could not import 'run'.

となり、実行できませんでした。
どうやら~/binディレクトリ内のパスがずれていそうですが、正しいディレクトリ内の構成を教えていただけないでしょうか？

**Comment by Trunkene** [comment]
十分確認せず済みません。とりあえず下記のような形で実施いただけますでしょうか？

$ git clone https://github.com/Trunkene/volumio_jpradio ./aaa
$ cd aaa
$ cp -r -f -v ./* ~/
$ cd ../
$ rm -r -f ./aaa

**Comment by igoigo15** [comment]
ありがとうございます！
radikoを実行した際、
SSLのエラー
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
が出ましたが、
https://end0tknr.hateblo.jp/entry/20210312/1615498434
に倣って/home/volumio/radiko/radiko/radiko.pyの冒頭に
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
を追記して無事動作しました。
→セキュリティ的には問題ありそうですが、応急処置として確認できました。

**Comment by Trunkene** [comment]
おぉ！
数か月前Volumio3にアップデートした際に、インストールしなおした際はご報告のエラーは確認できなかったのですが環境や細かいバージョンの違いかもしれないですね。他の方が同様の現象になった際に役立つと思いますので情報ありがとうございました！
